options:
  logging: CLOUD_LOGGING_ONLY

steps:
# Step 1: Build the Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/clinical-assistant-429217/clinical-assistant/clinical-assistant-app:latest', '.']

# Step 2: Push the Docker image to Google Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/clinical-assistant-429217/clinical-assistant/clinical-assistant-app:latest']

# Step 3: Apply the Kubernetes configuration for the Clinical Assistant app
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'kubernetes/clinical-assistant-app.yaml']

# Step 4: Wait for the LoadBalancer to get an external IP address and update Ingress configuration
- name: 'gcr.io/cloud-builders/kubectl'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      # Wait for the LoadBalancer IP to be assigned
      echo "Waiting for the LoadBalancer IP address..."
      for i in {1..30}; do
        INGRESS_IP=$(kubectl get svc clinical-assistant-service -n prod-namespace -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
        if [ -n "$INGRESS_IP" ]; then
          break
        fi
        echo "Attempt $i: LoadBalancer IP not assigned yet. Retrying in 10 seconds..."
        sleep 10
      done
      
      if [ -z "$INGRESS_IP" ]; then
        echo "LoadBalancer IP address not found. Exiting..."
        exit 1
      fi
      
      DNS_NAME="$INGRESS_IP.xip.io"
      echo "Using DNS name: $DNS_NAME"
      
      # Replace placeholder in ingress.yaml with the actual IP address
      gsutil cat kubernetes/ingress.yaml | sed "s/YOUR_IP_ADDRESS/$INGRESS_IP/g" kubernetes/ingress.yaml > kubernetes/ingress-temp.yaml
      
      # Apply the updated Ingress configuration
      kubectl apply -f kubernetes/ingress-temp.yaml

# Step 5: Trigger Cloud Deploy for the new release
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      gcloud deploy releases create clinical-assistant-release-$(date +%Y%m%d-%H%M%S) \
      --project=clinical-assistant-429217 \
      --region=us-central1 \
      --delivery-pipeline=fastapi-pipeline \
      --images=clinical-assistant-container=us-central1-docker.pkg.dev/clinical-assistant-429217/clinical-assistant/clinical-assistant-app:latest \
      --annotations=commit-sha=$(git rev-parse HEAD) \
      --skaffold-file=skaffold.yaml

images:
- 'us-central1-docker.pkg.dev/clinical-assistant-429217/clinical-assistant/clinical-assistant-app:latest'

timeout: '1200s'  # Set a timeout for the build process
