apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: main-ingress
  namespace: prod-namespace
  annotations:
    kubernetes.io/ingress.class: "gce"
    # networking.gke.io/managed-certificates: "fastapi-managed-cert"
spec:
  rules:
  - host: 34.172.105.113.xip.io
    http:
      paths:
      - path: /api/*
        pathType: ImplementationSpecific
        backend:
          service:
            name: fastapi-service
            port:
              number: 80
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: clinical-assistant-service
            port:
              number: 80

